#!/usr/bin/env sh

# Clone repositories managed by this project
set -e
projectRoot=$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)

(
  cd "${projectRoot}"

  printf "\nCloning repositories\n"

  test -d fcp-fd-landing-page\
    && >&2 echo "The 'fcp-fd-landing-page' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-landing-page.git
  test -d fcp-fd-auth\
    && >&2 echo "The 'fcp-fd-auth' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-auth.git
  test -d fcp-fd-ingress\
    && >&2 echo "The 'fcp-fd-ingress' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-ingress.git
  test -d fcp-fd-data\
    && >&2 echo "The 'fcp-fd-data' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-data.git
  test -d fcp-fd-messages\
    && >&2 echo "The 'fcp-fd-messages' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-messages.git
  test -d fcp-fd-messages-processor\
    && >&2 echo "The 'fcp-fd-messages-processor' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-messages-processor.git
  test -d fcp-fd-customer-receiver-messages\
    && >&2 echo "The 'fcp-fd-customer-receiver-messages' repository already exists. Skipping." \
    || git clone https://github.com/DEFRA/fcp-fd-customer-receiver-messages.git
)