include:
  - service-compose/fcp-fd-file-retriever.yaml
  - service-compose/fcp-fd-file-processor.yaml
  - service-compose/fcp-fd-data.yaml
  - service-compose/fcp-fd-comms.yaml
  - local-setup/fcp-fd-local-setup.yaml
services:
  fcp-fd-postgres:
    image: postgres:16.4-alpine
    container_name: fcp-fd-postgres
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USERNAME:-postgres} -d postgres
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - fcp-fd
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fcp-fd-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: fcp-fd-azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - fcp-fd
    env_file:
      - .env
    environment:
      AZURITE_ACCOUNTS: |
        ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}:${AZURITE_ACCESS_KEY:-test};${CLN_STORAGE_ACCOUNT_NAME:-cln}:${AZURITE_ACCESS_KEY:-test};${MAL_STORAGE_ACCOUNT_NAME:-mal}:${AZURITE_ACCESS_KEY:-test}
    volumes:
      - azurite_data:/data
networks:
  fcp-fd:
    name: fcp-fd
    driver: bridge
volumes:
  postgres_data: null
  azurite_data: null
