#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/fcp-fd-core [OPTION...]
    Open services in VS Code.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"

code ./fcp-fd-auth;
code ./fcp-fd-comms;
code ./fcp-fd-customer-receiver-messages;
code ./fcp-fd-data;
code ./fcp-fd-file-processor;
code ./fcp-fd-file-receiver;
code ./fcp-fd-file-retriever;
code ./fcp-fd-ingress;
code ./fcp-fd-landing-page;
code ./fcp-fd-messages;
code ./fcp-fd-messages-processor;
code ./fcp-fd-probe;
code ./fcp-fd-probe-alerts;