#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^fcp-fd$ --format={{.Name}})" ]; then
  echo "Creating fcp-fd Docker network"
  docker network create fcp-fd
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"
sfd="true"
receivers="true"

show_help() {
  echo "
    Usage: path/to/fcp-fd-core [OPTION...]
    Run services.

    Options:
      -h, --help               display this help text
      -d, --data-only          run fcp-fd-data and receivers only no other SFD services
      -r, --receivers-disabled run fcp-sfd with fcp-fd-data but without receiver services

    "
}

while :; do
  case $1 in    
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac
  shift
done

cd "${projectRoot}"

./fcp-fd-auth/scripts/start -d;
./fcp-fd-comms/scripts/start -d;
./fcp-fd-customer-receiver-messages/scripts/start -d;
./fcp-fd-data/scripts/start -d;
./fcp-fd-file-processor/scripts/start -d;
./fcp-fd-file-receiver/scripts/start -d;
./fcp-fd-landing-page/scripts/start -d;
./fcp-fd-messages/scripts/start -d;
./fcp-fd-messages-processor/scripts/start -d;
./fcp-fd-probe/scripts/start -d;
./fcp-fd-probe-alerts/scripts/start -d;