#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc/pay/services [OPTION...]
    Stop services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./fcp-fd-auth && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-customer-receiver-messages && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-data && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-file-receiver && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-file-processor && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-ingress && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-landing-page && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-messages && \
  docker-compose down $@
cd "${projectRoot}"
cd ./fcp-fd-messages-processor && \
  docker-compose down $@