include:
  - fcp-fd-service-bus.yaml
services:
  fcp-fd-local-setup:
    build:
      context: ../local-setup
    image: fcp-fd-local-setup
    container_name: fcp-fd-local-setup
    depends_on:
      fcp-fd-service-bus:
        condition: service_started
      fcp-fd-postgres:
        condition: service_healthy
      fcp-fd-azurite: 
        condition: service_started
    networks:
      - fcp-fd
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-fcp-fd-postgres}
      SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ppp}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
    volumes:
      - ../../fcp-fd-comms/changelog:/liquibase/services/fcp_fd_comms/changelog
      - ../../fcp-fd-data/changelog:/liquibase/services/fcp_fd_data/changelog

  fcp-fd-postgres:
    image: postgres:16.4-alpine
    container_name: fcp-fd-postgres
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USERNAME:-postgres} -d postgres
      interval: 5s
      retries: 10
      timeout: 5s
    networks:
      - fcp-fd
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  fcp-fd-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: fcp-fd-azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - fcp-fd
    env_file:
      - ../.env
    environment:
      AZURITE_ACCOUNTS: |
        ${DMZ_STORAGE_ACCOUNT_NAME:-dmz}:${AZURITE_ACCESS_KEY:-test};${CLN_STORAGE_ACCOUNT_NAME:-cln}:${AZURITE_ACCESS_KEY:-test};${MAL_STORAGE_ACCOUNT_NAME:-mal}:${AZURITE_ACCESS_KEY:-test}
    volumes:
      - azurite_data:/data

  fcp-fd-mockoon-server:
    image: mockoon/cli:latest
    container_name: fcp-fd-mockoon-server
    command: ["--data", "data", "--port", "3000"]
    ports: 
      - 8080:3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://fcp-fd-mockoon-server:3000/healthy || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - fcp-fd
    volumes:
      - ./notify.json:/data:readonly

volumes:
  postgres_data:
  azurite_data: